### ISSUE TITLE
Thank you for the lib! Could you publish 0.0.5?

### ISSUE THREAD

**Issue by donaldpipowitch** [ehmicky/get-sourcemaps#1]
Hi there!

Thank you for the lib. I currently try to create a tool and I'd like to use your lib. Could you publish `0.0.5`, because `"engines"` was changed there to allow lower Node versions?

Thank you and have a nice day :)

**Comment by ehmicky** [comment]
Hi @donaldpipowitch 

Thanks!

I just published `0.1.0`.

Please note this library is not documented yet, because I built it for another project, which has not started yet.

**Comment by ehmicky** [comment]
Also I want to make the code work on browsers as well. Until I do that, I plan to keep this library undocumented and will not to promote it outside of GitHub.

**Comment by donaldpipowitch** [comment]
Cool, thank you. I didn't know `convert-source-map`. Maybe I can use this one as well, so you don't feel rushed by me :)
